"""Reality Studio enums, controlled vocabularies, and legal transition maps (H-014A)."""

API_PREFIX = "/reality/v1"
TENANT_ID = "stratex-habitat"  # single demo tenant; server-derived, never client-supplied

# --- Collections ---------------------------------------------------------
C_SPATIAL = "reality_spatial_entities"
C_FRAMES = "reality_coordinate_frames"
C_SCANS = "reality_scan_sessions"
C_ARTIFACTS = "reality_artifact_manifests"
C_EXISTING = "reality_existing_model_versions"
C_DESIGN = "reality_design_model_versions"

# --- Truth classifications (Phase 4) -------------------------------------
VERIFIED_EXISTING = "VERIFIED_EXISTING"
MEASURED_EXISTING = "MEASURED_EXISTING"
ESTIMATED_EXISTING = "ESTIMATED_EXISTING"
INFERRED_EXISTING = "INFERRED_EXISTING"
HOMEOWNER_REPORTED = "HOMEOWNER_REPORTED"
PROPOSED_DESIGN = "PROPOSED_DESIGN"
AI_SUGGESTED_DESIGN = "AI_SUGGESTED_DESIGN"
PROFESSIONALLY_REVIEWED_DESIGN = "PROFESSIONALLY_REVIEWED_DESIGN"
APPROVED_FOR_BUILD_PACKAGE = "APPROVED_FOR_BUILD_PACKAGE"
COMPLETED_AS_BUILT = "COMPLETED_AS_BUILT"
UNKNOWN = "UNKNOWN"

TRUTH_CLASSES = {
    VERIFIED_EXISTING, MEASURED_EXISTING, ESTIMATED_EXISTING, INFERRED_EXISTING,
    HOMEOWNER_REPORTED, PROPOSED_DESIGN, AI_SUGGESTED_DESIGN,
    PROFESSIONALLY_REVIEWED_DESIGN, APPROVED_FOR_BUILD_PACKAGE, COMPLETED_AS_BUILT, UNKNOWN,
}

# Truth classes a Habitat-only actor may NEVER self-promote to (require Core/
# Passport/professional-review authority). Fail closed in H-014A.
RESTRICTED_TRUTH_CLASSES = {
    VERIFIED_EXISTING, PROFESSIONALLY_REVIEWED_DESIGN,
    APPROVED_FOR_BUILD_PACKAGE, COMPLETED_AS_BUILT,
}

# Truth classes Habitat may author for candidate existing geometry.
HABITAT_EXISTING_CLASSES = {MEASURED_EXISTING, ESTIMATED_EXISTING, INFERRED_EXISTING,
                            HOMEOWNER_REPORTED, UNKNOWN}
DESIGN_CLASSES = {PROPOSED_DESIGN, AI_SUGGESTED_DESIGN}

CONFIDENCE_LEVELS = {"HIGH", "MEDIUM", "LOW", "UNKNOWN"}

# --- Source classifications (Phase 4) ------------------------------------
SOURCE_CLASSES = {
    "PASSPORT_PROJECTION", "CORE_APPROVED", "LIDAR_CAPTURE", "PHOTOGRAMMETRY",
    "DRONE_RECONSTRUCTION", "THERMAL_PROCESSING", "HOMEOWNER_INPUT",
    "PROFESSIONAL_INPUT", "DETERMINISTIC_REFERENCE_FIXTURE", "AI_INFERENCE", "UNKNOWN_SOURCE",
}

# --- Existing/proposed/completed classification --------------------------
EXISTING = "EXISTING"
PROPOSED = "PROPOSED"
COMPLETED = "COMPLETED"
EXISTENCE_STATES = {EXISTING, PROPOSED, COMPLETED}

# --- Spatial entity types (Phase 5) --------------------------------------
ENTITY_TYPES = {
    "PROPERTY", "BUILDING", "LEVEL", "ZONE", "ROOM", "EXTERIOR_ELEVATION",
    "ROOF_PLANE", "SURFACE", "OPENING", "DOOR", "WINDOW", "STAIR", "CEILING",
    "FLOOR", "WALL", "STRUCTURAL_ELEMENT", "SYSTEM", "FIXTURE", "EQUIPMENT",
    "PRODUCT_INSTANCE", "ANNOTATION", "FINDING_LOCATION", "DESIGN_ELEMENT",
    "PROPOSED_ADDITION", "SITE_FEATURE",
}
# Entity types that are a kind of surface (openings live on these)
SURFACE_LIKE = {"SURFACE", "WALL", "FLOOR", "CEILING", "EXTERIOR_ELEVATION", "ROOF_PLANE"}
OPENING_LIKE = {"OPENING", "DOOR", "WINDOW"}
# Proposed-only entity types (never allowed in an existing-model snapshot)
PROPOSED_ONLY_TYPES = {"DESIGN_ELEMENT", "PROPOSED_ADDITION"}

GEOMETRY_TYPES = {"MESH", "PLANE", "POLYGON", "POLYLINE", "POINT", "BBOX", "PARAMETRIC", "NONE"}
UNITS = {"METRIC_M"}
ACCESS_CLASSES = {"HOMEOWNER", "CONTRACTOR", "PROFESSIONAL", "INTERNAL", "RESTRICTED_IMAGERY"}

# --- Coordinate frame types (Phase 6) ------------------------------------
FRAME_TYPES = {
    "PROPERTY_FRAME", "BUILDING_FRAME", "LEVEL_FRAME", "ROOM_FRAME",
    "SCAN_LOCAL_FRAME", "DRONE_LOCAL_FRAME", "MODEL_LOCAL_FRAME", "DESIGN_LOCAL_FRAME",
}
ORIGIN_STATES = {
    "PROVISIONAL", "CONTROL_POINT_ALIGNED", "EXTERIOR_MODEL_ALIGNED",
    "PROFESSIONALLY_ALIGNED", "SUPERSEDED",
}
TOLERANCE_CLASSES = {"VISUALIZATION", "PLANNING", "FIELD_REVIEW", "SURVEY_GRADE"}
AXIS_CONVENTION = "X_EAST_Y_NORTH_Z_UP"  # right-handed, meters

# --- Scan session (Phase 7) ----------------------------------------------
CAPTURE_TYPES = {
    "INTERIOR_LIDAR", "EXTERIOR_DRONE", "EXTERIOR_HANDHELD_LIDAR", "PHOTOGRAMMETRY",
    "THERMAL", "ROOM_RESCAN", "PARTIAL_AREA", "POST_COMPLETION",
}
SCAN_CREATED = "CREATED"
SCAN_CAPTURE_READY = "CAPTURE_READY"
SCAN_CAPTURE_IN_PROGRESS = "CAPTURE_IN_PROGRESS"
SCAN_CAPTURE_PAUSED = "CAPTURE_PAUSED"
SCAN_UPLOAD_PENDING = "UPLOAD_PENDING"
SCAN_UPLOAD_IN_PROGRESS = "UPLOAD_IN_PROGRESS"
SCAN_UPLOAD_COMPLETE = "UPLOAD_COMPLETE"
SCAN_PROCESSING_PENDING = "PROCESSING_PENDING"
SCAN_PROCESSING_IN_PROGRESS = "PROCESSING_IN_PROGRESS"
SCAN_QUALITY_REVIEW = "QUALITY_REVIEW"
SCAN_ACCEPTED = "ACCEPTED"
SCAN_REJECTED = "REJECTED"
SCAN_CANCELLED = "CANCELLED"
SCAN_EXPIRED = "EXPIRED"
SCAN_FAILED_RECOVERABLE = "FAILED_RECOVERABLE"
SCAN_FAILED_FINAL = "FAILED_FINAL"

SCAN_TERMINAL = {SCAN_ACCEPTED, SCAN_REJECTED, SCAN_CANCELLED, SCAN_EXPIRED, SCAN_FAILED_FINAL}

SCAN_LEGAL_TRANSITIONS = {
    SCAN_CREATED: {SCAN_CAPTURE_READY, SCAN_CANCELLED, SCAN_EXPIRED, SCAN_FAILED_RECOVERABLE},
    SCAN_CAPTURE_READY: {SCAN_CAPTURE_IN_PROGRESS, SCAN_CANCELLED, SCAN_EXPIRED, SCAN_FAILED_RECOVERABLE},
    SCAN_CAPTURE_IN_PROGRESS: {SCAN_CAPTURE_PAUSED, SCAN_UPLOAD_PENDING, SCAN_CANCELLED,
                               SCAN_EXPIRED, SCAN_FAILED_RECOVERABLE},
    SCAN_CAPTURE_PAUSED: {SCAN_CAPTURE_IN_PROGRESS, SCAN_CANCELLED, SCAN_EXPIRED, SCAN_FAILED_RECOVERABLE},
    SCAN_UPLOAD_PENDING: {SCAN_UPLOAD_IN_PROGRESS, SCAN_CANCELLED, SCAN_EXPIRED, SCAN_FAILED_RECOVERABLE},
    SCAN_UPLOAD_IN_PROGRESS: {SCAN_UPLOAD_COMPLETE, SCAN_CANCELLED, SCAN_EXPIRED, SCAN_FAILED_RECOVERABLE},
    SCAN_UPLOAD_COMPLETE: {SCAN_PROCESSING_PENDING, SCAN_CANCELLED, SCAN_EXPIRED, SCAN_FAILED_RECOVERABLE},
    SCAN_PROCESSING_PENDING: {SCAN_PROCESSING_IN_PROGRESS, SCAN_CANCELLED, SCAN_EXPIRED, SCAN_FAILED_RECOVERABLE},
    SCAN_PROCESSING_IN_PROGRESS: {SCAN_QUALITY_REVIEW, SCAN_CANCELLED, SCAN_EXPIRED, SCAN_FAILED_RECOVERABLE},
    SCAN_QUALITY_REVIEW: {SCAN_ACCEPTED, SCAN_REJECTED, SCAN_CANCELLED, SCAN_EXPIRED, SCAN_FAILED_RECOVERABLE},
    SCAN_FAILED_RECOVERABLE: {SCAN_CAPTURE_READY, SCAN_UPLOAD_PENDING, SCAN_PROCESSING_PENDING,
                              SCAN_CANCELLED, SCAN_FAILED_FINAL, SCAN_EXPIRED},
    SCAN_ACCEPTED: set(), SCAN_REJECTED: set(), SCAN_CANCELLED: set(),
    SCAN_EXPIRED: set(), SCAN_FAILED_FINAL: set(),
}

# --- Existing model version states (Phase 9) -----------------------------
EM_DRAFT_CANDIDATE = "DRAFT_CANDIDATE"
EM_QUALITY_REVIEW = "QUALITY_REVIEW"
EM_ACCEPTED = "ACCEPTED"
EM_REJECTED = "REJECTED"
EM_SUPERSEDED = "SUPERSEDED"
EM_TERMINAL = {EM_REJECTED}  # ACCEPTED is immutable but can be SUPERSEDED by a newer version
EM_LEGAL_TRANSITIONS = {
    EM_DRAFT_CANDIDATE: {EM_QUALITY_REVIEW, EM_REJECTED},
    EM_QUALITY_REVIEW: {EM_ACCEPTED, EM_REJECTED},
    EM_ACCEPTED: {EM_SUPERSEDED},
    EM_REJECTED: set(),
    EM_SUPERSEDED: set(),
}

# --- Design model version states -----------------------------------------
DM_DRAFT = "DRAFT"
DM_ALTERNATIVES = "ALTERNATIVES_REVIEW"
DM_SUPERSEDED = "SUPERSEDED"
DESIGN_MODEL_STATES = {DM_DRAFT, DM_ALTERNATIVES, DM_SUPERSEDED}

# --- Artifact types (Phase 8) --------------------------------------------
ARTIFACT_TYPES = {
    "RAW_LIDAR", "RAW_RGB", "RAW_THERMAL", "POINT_CLOUD", "MESH", "TEXTURE",
    "ORTHOMOSAIC", "PANORAMA", "FLOOR_PLAN", "MODEL_PREVIEW", "FULL_RESOLUTION_MODEL",
    "DERIVED_MEASUREMENTS", "DESIGN_VERSION_EXPORT", "REPORT_RENDER", "OTHER_GOVERNED_ARTIFACT",
}
RAW_ARTIFACT_TYPES = {"RAW_LIDAR", "RAW_RGB", "RAW_THERMAL"}
RESTRICTED_IMAGERY_TYPES = {"RAW_RGB", "RAW_THERMAL", "PANORAMA"}

# --- Audit event types (Phase 12) ----------------------------------------
A_FRAME_CREATED = "REALITY_COORDINATE_FRAME_CREATED"
A_FRAME_SUPERSEDED = "REALITY_COORDINATE_FRAME_SUPERSEDED"
A_SCAN_CREATED = "REALITY_SCAN_SESSION_CREATED"
A_SCAN_TRANSITIONED = "REALITY_SCAN_SESSION_TRANSITIONED"
A_SCAN_REJECTED = "REALITY_SCAN_SESSION_REJECTED"
A_ARTIFACT_CREATED = "REALITY_ARTIFACT_MANIFEST_CREATED"
A_EXISTING_CREATED = "REALITY_EXISTING_MODEL_CREATED"
A_EXISTING_ACCEPTED = "REALITY_EXISTING_MODEL_ACCEPTED"
A_EXISTING_REJECTED = "REALITY_EXISTING_MODEL_REJECTED"
A_EXISTING_SUPERSEDED = "REALITY_EXISTING_MODEL_SUPERSEDED"
A_DESIGN_CREATED = "REALITY_DESIGN_MODEL_CREATED"
A_TRUTH_PROMOTION_REJECTED = "REALITY_TRUTH_PROMOTION_REJECTED"
A_VERSION_CONFLICT = "REALITY_VERSION_CONFLICT"
A_REFERENCE_ROOM_BOOTSTRAPPED = "REALITY_REFERENCE_ROOM_BOOTSTRAPPED"
A_CROSS_TENANT_REJECTED = "REALITY_CROSS_TENANT_ACCESS_REJECTED"
A_INVALID_RELATIONSHIP_REJECTED = "REALITY_INVALID_RELATIONSHIP_REJECTED"
A_SPATIAL_ENTITY_CREATED = "REALITY_SPATIAL_ENTITY_CREATED"

PRIVILEGED_ROLES = {"executive", "broker_admin", "reviewer"}

# =========================================================================
# H-014B — Real LiDAR capture proof + AI Scan Quality Guardian
# =========================================================================

# --- Additional collections ----------------------------------------------
C_UPLOAD_SESSIONS = "reality_upload_sessions"
C_UPLOAD_CHUNKS = "reality_upload_chunks"

# --- Native (iOS RoomPlan / ARKit) capture states ------------------------
# The native client exposes a small, explicit capture state machine. Each
# native state maps to EXACTLY ONE canonical backend scan-session state so the
# governed lifecycle remains the single source of truth (never the device).
NATIVE_CAPTURE_STATES = {
    "IDLE", "AUTHORIZED", "READY", "CAPTURING", "PAUSED",
    "FINALIZING", "UPLOADING", "UPLOADED", "PROCESSING", "COMPLETE",
    "FAILED", "CANCELLED",
}
NATIVE_TO_SCAN_STATE = {
    "IDLE": SCAN_CREATED,
    "AUTHORIZED": SCAN_CREATED,
    "READY": SCAN_CAPTURE_READY,
    "CAPTURING": SCAN_CAPTURE_IN_PROGRESS,
    "PAUSED": SCAN_CAPTURE_PAUSED,
    "FINALIZING": SCAN_UPLOAD_PENDING,
    "UPLOADING": SCAN_UPLOAD_IN_PROGRESS,
    "UPLOADED": SCAN_UPLOAD_COMPLETE,
    "PROCESSING": SCAN_PROCESSING_IN_PROGRESS,
    "COMPLETE": SCAN_QUALITY_REVIEW,
    "FAILED": SCAN_FAILED_RECOVERABLE,
    "CANCELLED": SCAN_CANCELLED,
}

# --- Resumable upload session lifecycle ----------------------------------
UP_INITIATED = "INITIATED"
UP_IN_PROGRESS = "IN_PROGRESS"
UP_ASSEMBLING = "ASSEMBLING"
UP_COMPLETED = "COMPLETED"
UP_ABORTED = "ABORTED"
UP_FAILED = "FAILED"
UPLOAD_TERMINAL = {UP_COMPLETED, UP_ABORTED}

MAX_CHUNK_BYTES = 8 * 1024 * 1024            # < 16 MB BSON document limit (chunk staged in Mongo)
MIN_CHUNK_BYTES = 1
MAX_UPLOAD_BYTES = 2 * 1024 * 1024 * 1024    # 2 GiB governed per-artifact cap
MAX_TOTAL_CHUNKS = 4096                       # governed fan-out cap

# --- Scan Quality Guardian verdicts --------------------------------------
GUARDIAN_VERSION = "1.0.0"
GUARDIAN_PASS = "PASS"
GUARDIAN_WARN = "WARN"
GUARDIAN_FAIL = "FAIL"
GUARDIAN_VERDICTS = {GUARDIAN_PASS, GUARDIAN_WARN, GUARDIAN_FAIL}
COVERAGE_COMPLETE = "COMPLETE"
COVERAGE_PARTIAL = "PARTIAL"
COVERAGE_INCOMPLETE = "INCOMPLETE"

# --- H-014B audit event types --------------------------------------------
A_CAPTURE_PROGRESS = "REALITY_CAPTURE_PROGRESS_RECORDED"
A_UPLOAD_INITIATED = "REALITY_UPLOAD_INITIATED"
A_UPLOAD_COMPLETED = "REALITY_UPLOAD_COMPLETED"
A_UPLOAD_CHECKSUM_MISMATCH = "REALITY_UPLOAD_CHECKSUM_MISMATCH"
A_UPLOAD_ABORTED = "REALITY_UPLOAD_ABORTED"
A_GUARDIAN_EVALUATED = "REALITY_SCAN_GUARDIAN_EVALUATED"
A_CANDIDATE_GENERATED = "REALITY_CANDIDATE_MODEL_GENERATED"
A_CAPTURE_PROOF_BOOTSTRAPPED = "REALITY_CAPTURE_PROOF_BOOTSTRAPPED"
